## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

In [15]:
N = 10
x = np.arange( 0, N )
x = x[::-1]

In [16]:
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [30]:
N = 10
y = np.diag(np.arange(1, N)[::-1])
print(y)

print('Сумма элементов главной диагонали = ',sum(y[i][i] for i in range(N-1)))

[[9 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 4 0 0 0]
 [0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 1]]
Сумма элементов главной диагонали =  45


## Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [33]:
m = np.array([[4., 2., 1.], [1., 3., 0], [0., 5., 4.]])
v = np.array([4., 12., -3.])

np.linalg.solve(m, v)

array([ 0.46666667,  3.84444444, -5.55555556])

## Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”


In [52]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между 
этим пользователем и всеми пользователями из массива user_stats

In [74]:
def cosine_ ( users_stats, next_user_stats ):
    return np.dot( users_stats, next_user_stats ) / ( np.linalg.norm( users_stats ) * np.linalg.norm( next_user_stats ) )

m = np.argmax(np.array([cosine_(row, next_user_stats) for row in users_stats]))

print('Пользователь', m, 'с покупками', users_stats[m] )
print('больше всего похож на', next_user_stats)

Пользователь 7 с покупками [0 1 1 0 0 0]
больше всего похож на [0 1 2 0 0 0]
